### ISSUE TITLE
PaulaM - Geo III

### ISSUE THREAD

**Issue by paulaRMachado** [Ironhack-data-bcn-april-2023/project-III-geospatial-data#7]
https://github.com/paulaRMachado/Project-III-GEO.git

**Comment by ta-data-bcn** [comment]
Heeelloo Paula 🚀

Good job on the third project, see below for comments :) 

**Organization of your files** 📚

- You didn't add your .env file and the organization of your repo looks great 🔝 

**README.md** ✍🏽

- Your README looks awesome. You walk the reader through the process you went through and show the results.
- I would take out the link to your html maps on the readme, and only leave the screenshots!

**The code** 👨🏽‍💻

- Good job doing Mongo queries & Foursquare API's, you could’ve done geoqueries too
- You’re functions are amazing, always  clear with docstrings and comments. WELL DONE!!!!!!!!!!!!! Everyone that ever reads your code will be grateful for that.
- There are some functions that can be greatly condensed. As you take everything you did and put it into a function, but sometimes doing a minifunction first so there is not as much repetition is recommended, also the use of dictionaries will reduce a lot the amount of code you will have!
- In general your code looks really good, good job Paula!!!!!🙌🏾 


**Viz** 🎨 

- Good Visualizations! Maybe I would’ve put markers instead of heatmap to see the venues, as they are all different and maybe the red zone is only red because it has a huge amount of Starbucks but not other venues!
Other than that good job Paula! MUITO BEM


In general, your project looks super good Paula, also good effort in doing the bonus too, shows the work you are putting in! You’ll see the rewards DON’T WORRY!!!!!!! AND DON’T STRESS 

Congraats and good luck on the next one!
